package oosd.sait.ipdbuddyapi.dto.job;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import oosd.sait.ipdbuddyapi.dto.billable.BillableItemsSummary;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;


@Data
@AllArgsConstructor
@NoArgsConstructor
public class JobResponseDTO {

    private Long jobId;
    private BigDecimal taxAmount;
    private BigDecimal savingsAmount;
    private BigDecimal grandTotalAmount;
    private String message;
    private LocalDate date;
    private String address;


    //Constructors generated by IntelliJ suggesting them - I'll have to look into why the lambda annotations dont cover this.
    public JobResponseDTO(Long id, LocalDate date, String address) {
    }

    public JobResponseDTO(Long id, LocalDate date, String address, List<BillableItemsSummary> itemsSummaryList) {
    }
}
